import BigNumber from "bignumber.js";

export const mockBalances = [
  {
    id: "XLM",
    token: {
      code: "XLM",
      type: "native",
    },
    total: new BigNumber("1000.5"),
    available: new BigNumber("1000.5"),
    minimumBalance: "1",
    buyingLiabilities: "0",
    sellingLiabilities: "0",
    tokenCode: "XLM",
    displayName: "XLM",
    imageUrl: "",
    currentPrice: new BigNumber("0.5"),
    percentagePriceChange24h: new BigNumber("0.02"),
    fiatCode: "USD",
    fiatTotal: "50.25",
  },
  {
    id: "USDC:GBDQOFC6SKCNBHPLZ7NXQ6MCKFIYUUFVOWYGNWQCXC2F4AYZ27EUWYWH",
    token: {
      code: "USDC",
      type: "",
    },
    total: new BigNumber("10"),
    available: new BigNumber("10"),
    minimumBalance: "1",
    buyingLiabilities: "0",
    sellingLiabilities: "0",
    tokenCode: "USDC",
    displayName: "USDC",
    imageUrl: "",
    currentPrice: new BigNumber("0.5"),
    percentagePriceChange24h: new BigNumber("0.02"),
    fiatCode: "USD",
    fiatTotal: "50.25",
  },
  {
    id: "FTT:GBDQOFC6SKCNBHPLZ7NXQ6MCKFIYUUFVOWYGNWQCXC2F4AYZ27EUWYWH",
    token: {
      code: "FTT",
      type: "",
    },
    total: new BigNumber("20"),
    available: new BigNumber("20"),
    minimumBalance: "1",
    buyingLiabilities: "0",
    sellingLiabilities: "0",
    tokenCode: "FTT",
    displayName: "FTT",
    imageUrl: "",
    currentPrice: new BigNumber("0.3"),
    percentagePriceChange24h: new BigNumber("0.5"),
    fiatCode: "USD",
    fiatTotal: "50.25",
  },
];
