import { isProd } from "helpers/isEnv";
import Config from "react-native-config";

type EnvConfigType = {
  AMPLITUDE_API_KEY: string;
  AMPLITUDE_EXPERIMENT_DEPLOYMENT_KEY: string;

  FREIGHTER_BACKEND_URL: string;
  FREIGHTER_BACKEND_V2_URL: string;

  WALLET_KIT_PROJECT_ID: string;
  WALLET_KIT_MT_NAME: string;
  WALLET_KIT_MT_DESCRIPTION: string;
  WALLET_KIT_MT_URL: string;
  WALLET_KIT_MT_ICON: string;
  WALLET_KIT_MT_REDIRECT_NATIVE: string;

  SENTRY_DSN: string;

  ANDROID_DEBUG_KEYSTORE_PASSWORD: string;
  ANDROID_DEBUG_KEYSTORE_ALIAS: string;
  ANDROID_DEV_KEYSTORE_PASSWORD: string;
  ANDROID_DEV_KEYSTORE_ALIAS: string;
  ANDROID_PROD_KEYSTORE_PASSWORD: string;
  ANDROID_PROD_KEYSTORE_ALIAS: string;
};

/**
 * Get environment-specific configuration based on bundle ID
 */
const getEnvConfig = (): EnvConfigType => ({
  // Let's avoid sending events to Amplitude while developing locally
  AMPLITUDE_API_KEY: __DEV__ ? "" : Config.AMPLITUDE_API_KEY,
  AMPLITUDE_EXPERIMENT_DEPLOYMENT_KEY:
    Config.AMPLITUDE_EXPERIMENT_DEPLOYMENT_KEY,

  SENTRY_DSN: Config.SENTRY_DSN,

  FREIGHTER_BACKEND_URL: Config.FREIGHTER_BACKEND_URL,
  FREIGHTER_BACKEND_V2_URL: Config.FREIGHTER_BACKEND_V2_URL,

  WALLET_KIT_PROJECT_ID: Config.WALLET_KIT_PROJECT_ID,
  WALLET_KIT_MT_URL: Config.WALLET_KIT_MT_URL,
  WALLET_KIT_MT_ICON: Config.WALLET_KIT_MT_ICON,

  // Get wallet kit metadata based on bundle ID
  WALLET_KIT_MT_NAME: isProd
    ? Config.WALLET_KIT_MT_NAME_PROD
    : Config.WALLET_KIT_MT_NAME_DEV,
  WALLET_KIT_MT_DESCRIPTION: isProd
    ? Config.WALLET_KIT_MT_DESCRIPTION_PROD
    : Config.WALLET_KIT_MT_DESCRIPTION_DEV,
  WALLET_KIT_MT_REDIRECT_NATIVE: isProd
    ? Config.WALLET_KIT_MT_REDIRECT_NATIVE_PROD
    : Config.WALLET_KIT_MT_REDIRECT_NATIVE_DEV,

  ANDROID_DEBUG_KEYSTORE_PASSWORD: Config.ANDROID_DEBUG_KEYSTORE_PASSWORD,
  ANDROID_DEBUG_KEYSTORE_ALIAS: Config.ANDROID_DEBUG_KEYSTORE_ALIAS,
  ANDROID_DEV_KEYSTORE_PASSWORD: Config.ANDROID_DEV_KEYSTORE_PASSWORD,
  ANDROID_DEV_KEYSTORE_ALIAS: Config.ANDROID_DEV_KEYSTORE_ALIAS,
  ANDROID_PROD_KEYSTORE_PASSWORD: Config.ANDROID_PROD_KEYSTORE_PASSWORD,
  ANDROID_PROD_KEYSTORE_ALIAS: Config.ANDROID_PROD_KEYSTORE_ALIAS,
});

export const EnvConfig = getEnvConfig();
