# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "75G8D5L857",
      issuer_id: "aee30e88-5312-413f-8f0f-0413f21d7d9e",
      key_filepath: "./fastlane/AuthKey_75G8D5L857.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    increment_build_number(xcodeproj: "freighter-mobile.xcodeproj")
    build_app(workspace: "freighter-mobile.xcworkspace", scheme: "freighter-mobile-dev")
    upload_to_testflight
  end
end
