#!/bin/bash

echo 'Cleaning all the things';
yarn gradle-clean;
yarn node-clean;
rm -rf $TMPDIR/react-*;
rm -rf $TMPDIR/npm-*;
cd ios;
rm -rf Pods;
rm -rf Podfile.lock;
rm -rf build;
npm cache clean --force;
pod cache clean --all;
cd ../android;
rm -rf build;
cd ..;
rm -rf ~/Library/Developer/Xcode/DerivedData;
rm -rf "${HOME}/Library/Caches/CocoaPods";
rm -rf "`pwd`/Pods/";
echo 'Done cleaning!';