name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["main"]
  schedule:
    - cron: '20 17 * * *'

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v5

      - run: semgrep ci --sarif > semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # Map finding severity to Critical (9.0) or High (8.0)
      - name: Override SARIF severities for GitHub
        run: |
          apt-get update && apt-get install -y jq
          jq '
            .runs[].results |= map(
              if (.level == "error" or (.properties.severity == "Critical")) then
                .properties["security-severity"] = "9.0"
              elif (.level == "warning" or (.properties.severity == "High")) then
                .properties["security-severity"] = "8.0"
              else
                .properties["security-severity"] = "8.0"
              end
            )
          ' semgrep.sarif > semgrep-override.sarif
          mv semgrep-override.sarif semgrep.sarif

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif
        if: always()
